version: '3.1'

services:

  mongo:
    image: mongo:3-xenial
    volumes:
       - type: bind
         source: ./database-storage 
         target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks: 
      - dbnet1

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks: 
      - dbnet1

networks: 
  dbnet1: